### ISSUE TITLE
Make credit card not required for 100% discount - CiviMember

### ISSUE THREAD

**Issue by bcobin** [dlobo/org.civicrm.module.cividiscount#86] opened 2015-02-13 22:23 UTC
Yes - I know this has already been brought up (and marked as outside the scope of the module), but I'm wondering if anything's been done in the intervening time. I suspect something's been done insofar as the CC box disappears for Events when the amount goes to 0 - but the same doesn't happen for Memberships.

https://github.com/dlobo/org.civicrm.module.cividiscount/issues/10

My situation is as follows: The organization has different sponsorship levels; a Gold Sponsorship will include 5 yearly memberships and so on. If a sponsored member uses the discount code, the amount will go to $0 as expected - but the CC fields still appear and are mandatory.

Nobody would enter a CC number in this case - would you? So we can't use CiviDiscount for user-entered sponsored Memberships, which is unfortunate. (We'll need to add the members manually.)

This was a shock to me - with Events, everything works fine - the CC box disappears. I didn't expect Memberships to act differently, but there we are.

This was evidently fixed for Events - can the same functionality be applied for Memberships? If I was a coder, I'd dig in, but I'm not. The site is http://usgbc-li.org, BTW.

Any ideas? Any guidance or workarounds greatly appreciated… thanks!

Oh - I'm on Civi 4.4.5 - haven't made the jump to 4.5 seeing that CiviDiscount doesn't seem to be supported.

**Comment by bcobin** [comment] 2015-07-07 15:41
This is still not fixed - see screenshots, attached. This is with CiviDiscount 3.1, which seems to be the current production release. I'm now running Civi 4.6.4.

It seems that there's been a lot of work done here - if this has been fixed in development or beta code, what do I need to do to get this working? Thanks in advance...

![screen shot 2015-07-07 at 11 12 44 am](https://cloud.githubusercontent.com/assets/7141113/8549961/9474e9fc-249b-11e5-88b9-92ddc88dd9f1.png)

![screen shot 2015-07-07 at 11 13 07 am](https://cloud.githubusercontent.com/assets/7141113/8549966/9d50f8fe-249b-11e5-8e6f-1895b661d61f.png)

![screen shot 2015-07-07 at 11 13 18 am](https://cloud.githubusercontent.com/assets/7141113/8549969/a2dc909e-249b-11e5-80f3-b74db0956bdd.png)

**Comment by Stoob** [comment] 2015-07-13 17:39
![100-disc](https://cloud.githubusercontent.com/assets/1683473/8656275/67fdd136-294b-11e5-96eb-fd0cdafdba32.png)

Version 3.1 with CiviCRM 4.6.4 this bug is not fixed.  See attached.

**Comment by eileenmcnaughton** [comment] 2016-02-11 20:17
You should test this on 4.7 - might be fixed in that combo

**Comment by Stoob** [comment] 2016-02-11 22:15
In 4.6.12 and CiviDisc 3.1 this works.

**Comment by eileenmcnaughton** [comment] 2016-02-11 22:19
Cool - thanks for confirming.

**Comment by eileenmcnaughton** [comment] 2016-02-11 22:19
(if you are going to tell me I fixed it - I cannot remember anything that happened before Monday)

**Comment by Stoob** [comment] 2016-02-11 22:24
I forgot it was a problem, much less who fixed it.

**Comment by eileenmcnaughton** [comment] 2016-02-11 22:25
Probably something to do with a goat

**Closed** 2016-02-12 20:39 UTC

**Comment by HeatherO** [comment] 2016-12-12 13:20
I'm having a very similar issue on a recently upgraded CiviCRM version 4.6.23 and CiviDiscount version 3.3. It was previously working on the older versions.

They are two payment options on the membership sign up page: PayPal Standard and Pay Later. PayPal Standard is default and pre-selected on the Contribution page.

When you add a CiviDiscount of 100%, the payment types disappear, however, an error persists asking for a payment processor to be selected. I've set up a test page for ease of testing: https://pcrs-uk.org/civicrm/contribute/transact?reset=1&id=85

If you test with the discount code NSHI25XX16 you'll see the error
![error](https://cloud.githubusercontent.com/assets/6460807/21100755/ab315a3a-c06d-11e6-82a3-3f552861fb74.png)

**Comment by Stoob** [comment] 2016-12-12 18:58
That's a bummer, Heather.  Could please browse the repository and see what changed between 3.1 and 3.3 version of this extension?   There may have been a regression.

**Comment by mikecalverley** [comment] 2016-12-13 14:02
Hi Stoob,

It is to do with `main.js`. It unchecks the payment processor if the length of the discount code is greater than 0.

When you then submit the form, it is still looking for a payment processor (which has been unchecked), and thus throws the error.

**Comment by agileware** [comment] 2017-07-04 23:07
Passing by and noticed this thread. We had the same issue a while back and submitted this issue and PR which has since been merged. Just an FYI.

https://issues.civicrm.org/jira/browse/CRM-20360
https://github.com/civicrm/civicrm-core/pull/10080

**Comment by eileenmcnaughton** [comment] 2018-10-22 19:54
@mol3earth I don't think we would be fixing this for 4.6 releases - I think it's fixed in the latest release (currently 5.6.x)

**Comment by mol3earth** [comment] 2018-10-22 20:02
is there a patch? I was told that upgrading to 4.6.38 would fix this for us. we have extensions that won't work with 4.7/5. that is not ideal for us.

**Comment by eileenmcnaughton** [comment] 2018-10-22 20:05
@mol3earth I think the links posted on Jul 5 address for 5.x - not sure if it will for 4.6 -probably if you want extension fixes then you'll need to figure out how to get onto a later version - but that will obviously take you time to work through

**Comment by mol3earth** [comment] 2018-10-22 21:00
do you mean "ghost commented on Jul 4 2017" post? 

that is not the problem we are having. that solution stops showing the words Payment Options, we currently get this error: 
"Payment Error Response:
Error: Could not find payment information"

**Comment by eileenmcnaughton** [comment] 2018-10-22 21:15
Hmm ok - I'm not sure then :-(
